In [94]:
import pandas as pd
import numpy as np
import os

from folium.features import DivIcon
import folium
import pyproj
from pyproj import Proj, transform

%matplotlib inline  
import matplotlib.pyplot as plt 
import seaborn as sns 

import warnings
warnings.filterwarnings(action='ignore')

from tqdm import tqdm

def katec_to_wgs84(x, y):
    inProj  = Proj('+proj=tmerc +lat_0=38 +lon_0=128 +k=0.9999 +x_0=400000 +y_0=600000 +ellps=bessel +units=m +no_defs +towgs84=-115.80,474.99,674.11,1.16,-2.31,-1.63,6.43')
    outProj = Proj({ 'proj':'latlong', 'datum':'WGS84', 'ellps':'WGS84' })
    return transform( inProj, outProj, x, y )

WGS84 = { 'proj':'latlong', 'datum':'WGS84', 'ellps':'WGS84', }
KATEC = { 'proj':'tmerc', 'lat_0':'38N', 'lon_0':'128E', 'ellps':'bessel','x_0':'400000', 'y_0':'600000', 'k':'0.9999','towgs84':'-115.80,474.99,674.11,1.16,-2.31,-1.63,6.43'}
def wgs84_to_katec(longitude, latitude): # 경도 / 위도 순
    return transform( Proj(**WGS84), Proj(**KATEC), longitude, latitude )

In [95]:
pwd

'C:\\Users\\dudtj\\busan_moving_person\\data\\store_data'

In [96]:
cd ../data/store_data/

[WinError 3] 지정된 경로를 찾을 수 없습니다: '../data/store_data/'
C:\Users\dudtj\busan_moving_person\data\store_data

In [97]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: CE27-0A82

 C:\Users\dudtj\busan_moving_person\data\store_data 디렉터리

2021-08-16  오후 04:38    <DIR>          .
2021-08-16  오후 04:38    <DIR>          ..
2021-08-16  오후 04:38           959,535 PR_BUSANJINGU_STORE_2021.csv
2021-08-13  오후 07:24           796,518 PR_BUSANJINGU_STORE_2021.xlsx
               2개 파일           1,756,053 바이트
               2개 디렉터리  112,459,001,856 바이트 남음

In [144]:
storeDF = pd.read_csv("PR_BUSANJINGU_STORE_2021.csv", encoding="UTF-8")
len(storeDF)

17139

In [160]:
x = storeDF['경도']
y = storeDF['위도']

x[0]

129.0249385

In [165]:
a = []
for i in tqdm(range(0, 17139)):
    a.append(wgs84_to_katec(x[i], y[i]))
    
storeDF[['x', 'y']] = a
columns = ['상권업종대분류코드', '상권업종대분류명', '행정동코드', '행정동명', '경도', '위도','x','y']
storeDF = storeDF[columns]

100%|████████████████████████████████████████████████████████████████████████████| 17139/17139 [20:22<00:00, 14.02it/s]

In [169]:
storeDF

,상권업종대분류코드,상권업종대분류명,행정동코드,행정동명,경도,위도,x,y
0,Q,음식,26230740,개금1동,129.024938,35.151645,493582.220286,284124.900093
1,D,소매,26230720,가야2동,129.029713,35.151668,494017.217470,284131.905726
2,D,소매,26230600,전포1동,129.063037,35.157050,497047.205078,284760.949859
3,D,소매,26230520,부전2동,129.057661,35.151292,496564.214479,284116.943374
4,D,소매,26230510,부전1동,129.060278,35.161788,496790.195276,285283.945877
...,...,...,...,...,...,...,...,...
17134,R,학문/교육,26230560,양정1동,129.064923,35.174574,497198.179637,286706.950944
17135,Q,음식,26230510,부전1동,129.057299,35.160624,496520.204589,285151.941515
17136,F,생활서비스,26230600,전포1동,129.062861,35.155293,497033.208117,284565.949353
17137,R,학문/교육,26230670,당감1동,129.035320,35.161941,494516.201059,285276.913230
17138,Q,음식,26230510,부전1동,129.061408,35.158407,496897.205492,284909.947153

In [172]:
storeDF.to_csv("FPR_BUSANJINGU_STORE_2021.csv", index=False, encoding='cp949')

In [174]:
store_df = pd.read_csv("FPR_BUSANJINGU_STORE_2021.csv", encoding = "cp949")
store_df

,상권업종대분류코드,상권업종대분류명,행정동코드,행정동명,경도,위도,x,y
0,Q,음식,26230740,개금1동,129.024938,35.151645,493582.220286,284124.900093
1,D,소매,26230720,가야2동,129.029713,35.151668,494017.217470,284131.905726
2,D,소매,26230600,전포1동,129.063037,35.157050,497047.205078,284760.949859
3,D,소매,26230520,부전2동,129.057661,35.151292,496564.214479,284116.943374
4,D,소매,26230510,부전1동,129.060278,35.161788,496790.195276,285283.945877
...,...,...,...,...,...,...,...,...
17134,R,학문/교육,26230560,양정1동,129.064923,35.174574,497198.179637,286706.950944
17135,Q,음식,26230510,부전1동,129.057299,35.160624,496520.204589,285151.941515
17136,F,생활서비스,26230600,전포1동,129.062861,35.155293,497033.208117,284565.949353
17137,R,학문/교육,26230670,당감1동,129.035320,35.161941,494516.201059,285276.913230
17138,Q,음식,26230510,부전1동,129.061408,35.158407,496897.205492,284909.947153