In [1]:
import pandas as pd
import numpy as np

import glob

print('>>> 본 소스 작성 시 사용된 라이브러리 버전에 유의하세요!')
f'pd : {pd.__version__}  |  np : {np.__version__}'

>>> 본 소스 작성 시 사용된 라이브러리 버전에 유의하세요!

'pd : 1.0.5  |  np : 1.16.5'

## 개별 테이블 로드 및 내용 확인

In [2]:
dong_df = pd.read_pickle('서울특별시_월별_행정동별_총합.pkl')
dong_df.columns = ['시군구코드', '시군구명', '행정동코드', '행정동명', '연도별', '월별', '유동인구총합']
dong_df

      시군구코드 시군구명     행정동코드         행정동명   연도별  월별    유동인구총합
0     11110  종로구  11110540          삼청동  2019   1   5881315
1     11110  종로구  11110615  종로1.2.3.4가동  2019   1  61377525
2     11110  종로구  11110650          혜화동  2019   1  16015862
3     11110  종로구  11110680         창신2동  2019   1   2451402
4     11110  종로구  11110700         숭인1동  2019   1   7420365
...     ...  ...       ...          ...   ...  ..       ...
3387  11710  송파구  11710710         잠실6동  2020   4  31576430
3388  11740  강동구  11740540         명일2동  2020   4   8103775
3389  11740  강동구  11740590         암사3동  2020   4   9953712
3390  11740  강동구  11740610         천호2동  2020   4  23695173
3391  11740  강동구  11740650         성내2동  2020   4  15440134

[3392 rows x 7 columns]

In [3]:
time_df = pd.read_pickle('서울특별시_월별_행정동별_시간대별_총합.pkl')
time_df.columns = ['시군구코드', '시군구명', '행정동코드', '행정동명', '연도별', '월별', '시간대별', '유동인구총합']
time_df

       시군구코드 시군구명     행정동코드  행정동명   연도별  월별  시간대별   유동인구총합
0      11110  종로구  11110540   삼청동  2019   1     0    41591
1      11110  종로구  11110540   삼청동  2019   1     1    27499
2      11110  종로구  11110540   삼청동  2019   1     2    19626
3      11110  종로구  11110540   삼청동  2019   1     3    16739
4      11110  종로구  11110540   삼청동  2019   1     4    18858
...      ...  ...       ...   ...   ...  ..   ...      ...
81403  11740  강동구  11740650  성내2동  2020   4    19  1028258
81404  11740  강동구  11740650  성내2동  2020   4    20   915544
81405  11740  강동구  11740650  성내2동  2020   4    21   800761
81406  11740  강동구  11740650  성내2동  2020   4    22   666749
81407  11740  강동구  11740650  성내2동  2020   4    23   507530

[81408 rows x 8 columns]

In [4]:
sex_age_df = pd.read_pickle('서울특별시_월별_행정동별_성연령별_총합.pkl')
sex_age_df['sex'] = sex_age_df.sex_age.str[0].str.upper()
sex_age_df['age'] = sex_age_df.sex_age.str[1:].astype(int)
sex_age_df = sex_age_df.drop(columns=['sex_age'])[['sgg_cd', 'sgg_nm', 'admdong_cd', 'admdong_nm',
                                                   'year', 'month', 'sex', 'age', 'total']]
sex_age_df.columns = ['시군구코드', '시군구명', '행정동코드', '행정동명', '연도별', '월별', '성별', '연령대별', '유동인구총합']
sex_age_df

       시군구코드 시군구명     행정동코드  행정동명   연도별  월별 성별  연령대별  유동인구총합
0      11110  종로구  11110540   삼청동  2019   1  M     0     425
1      11110  종로구  11110540   삼청동  2019   1  M    10    6414
2      11110  종로구  11110540   삼청동  2019   1  M    15   58361
3      11110  종로구  11110540   삼청동  2019   1  M    20  230662
4      11110  종로구  11110540   삼청동  2019   1  M    25  386373
...      ...  ...       ...   ...   ...  .. ..   ...     ...
94971  11740  강동구  11740650  성내2동  2020   4  F    50  689935
94972  11740  강동구  11740650  성내2동  2020   4  F    55  766931
94973  11740  강동구  11740650  성내2동  2020   4  F    60  635374
94974  11740  강동구  11740650  성내2동  2020   4  F    65  335277
94975  11740  강동구  11740650  성내2동  2020   4  F    70  349920

[94976 rows x 9 columns]

## 월별 자치구별 전체, 월별 서울특별시 전체 테이블 생성

In [5]:
gu_df = dong_df.drop(columns=['행정동코드', '행정동명']).\
            groupby(['시군구코드', '시군구명', '연도별', '월별'])['유동인구총합'].sum().reset_index()
gu_df

     시군구코드 시군구명   연도별  월별     유동인구총합
0    11110  종로구  2019   1  220952023
1    11110  종로구  2019   2  186440892
2    11110  종로구  2019   3  243188937
3    11110  종로구  2019   4  230346929
4    11110  종로구  2020   1  255911132
..     ...  ...   ...  ..        ...
195  11740  강동구  2019   4  225760244
196  11740  강동구  2020   1  273505654
197  11740  강동구  2020   2  244157392
198  11740  강동구  2020   3  243858274
199  11740  강동구  2020   4  268415883

[200 rows x 5 columns]

In [6]:
seoul_df = gu_df.drop(columns=['시군구코드', '시군구명']).\
            groupby(['연도별', '월별'])['유동인구총합'].sum().reset_index()
seoul_df

    연도별  월별      유동인구총합
0  2019   1  7030050952
1  2019   2  6180754855
2  2019   3  7752288972
3  2019   4  7349055624
4  2020   1  7765303355
5  2020   2  7267661241
6  2020   3  7184765090
7  2020   4  7779529575

## 최종 엑셀 파일 저장 및 확인

In [7]:
with pd.ExcelWriter('서울특별시_유동인구_집계_최종.xlsx') as writer:
    seoul_df.to_excel(writer, sheet_name='월별 서울특별시 유동인구', index=False)
    gu_df.to_excel(writer, sheet_name='월별 자치구별 유동인구', index=False)
    dong_df.to_excel(writer, sheet_name='월별 행정동별 유동인구', index=False)
    sex_age_df.to_excel(writer, sheet_name='월별 성연령별 유동인구', index=False)
    time_df.to_excel(writer, sheet_name='월별 시간대별 유동인구', index=False)

# 파일 저장 확인
glob.glob('서울특별시_유동인구_집계_최종.xlsx')

['서울특별시_유동인구_집계_최종.xlsx']